# Generated by Django 2.1.7 on 2019-03-27 00:00

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swissgeo', '0002_auto_20190327_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='canton',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=21781),
        ),
    ]
