version: '3.1'

services:
  db:
    image: mdillon/postgis
    volumes:
      - ./scripts/postgis.sql:/docker-entrypoint-initdb.d/1_postgis.sql
      - ./scripts/cantons.sql:/docker-entrypoint-initdb.d/2_cantons.sql
    environment: 
      POSTGRES_DB: testGIS
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  web:
    #build: .
    #image: geoweb_web
		image: jpcik/geoweb
    command: ./manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
#    - redis
    entrypoint: /entrypoint.sh
    environment:
      DATABASE_URL: postgis://postgres:postgres@0.0.0.0:5432/testGIS